# -*- coding: utf-8 -*-
"""ShadowFox.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pHiNIYipXfC5I6bJeAhpMXSIJ15Vkwg2
"""

!pip install pyspellchecker tensorflow

from spellchecker import SpellChecker
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense
import numpy as np

spell = SpellChecker()

text = "I lvoe learnng new thngs"
words = text.split()
corrected = [spell.correction(w) for w in words]
print("Original text:", text)
print("Autocorrected text:", " ".join(corrected))

corpus = [
    "I love learning new things",
    "I love machine learning",
    "I enjoy reading books",
    "I enjoy coding in python",
    "This project uses neural networks",
    "I love programming in python",
    "Deep learning is fascinating",
    "Machine learning improves accuracy"
]

tokenizer = Tokenizer()
tokenizer.fit_on_texts(corpus)
total_words = len(tokenizer.word_index) + 1

input_sequences = []
for line in corpus:
    token_list = tokenizer.texts_to_sequences([line])[0]
    for i in range(1, len(token_list)):
        seq = token_list[:i+1]
        input_sequences.append(seq)

max_len = max([len(x) for x in input_sequences])
input_sequences = np.array(pad_sequences(input_sequences, maxlen=max_len, padding='pre'))

X = input_sequences[:, :-1]
y = input_sequences[:, -1]
y = tf.keras.utils.to_categorical(y, num_classes=total_words)

model = Sequential([
    Embedding(total_words, 64, input_length=max_len-1),
    LSTM(128),
    Dense(total_words, activation='softmax')
])
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.summary()

model.fit(X, y, epochs=200, verbose=1)

def predict_next_word(model, tokenizer, text, max_len):
    token_list = tokenizer.texts_to_sequences([text])[0]
    token_list = pad_sequences([token_list], maxlen=max_len-1, padding='pre')
    predicted = np.argmax(model.predict(token_list, verbose=0), axis=1)
    for word, index in tokenizer.word_index.items():
        if index == predicted:
            return word
    return None

seed_text = "I love"
print("Next word prediction for:", seed_text)
print("Predicted word:", predict_next_word(model, tokenizer, seed_text, max_len))

def autocorrect_and_predict(text):

    words = text.split()
    corrected = [spell.correction(w) for w in words]
    corrected_text = " ".join(corrected)


    next_word = predict_next_word(model, tokenizer, corrected_text, max_len)
    print("Input text:", text)
    print("Corrected text:", corrected_text)
    print("Predicted next word:", next_word)

autocorrect_and_predict("I lvoe")











import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

from google.colab import drive
drive.mount('/content/drive')
df = pd.read_csv('/content/drive/MyDrive/loan_prediction.csv')
df.head()

print(df.info())
print(df.describe())

print(df.isnull().sum())


df.fillna(df.mode().iloc[0], inplace=True)

sns.countplot(x='Loan_Status', data=df)
plt.title("Loan Approval Status Distribution")
plt.show()

encoder = LabelEncoder()
for col in df.columns:
    if df[col].dtype == 'object':
        df[col] = encoder.fit_transform(df[col])

X = df.drop('Loan_Status', axis=1)
y = df['Loan_Status']


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

cm = confusion_matrix(y_test, y_pred)
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

applicant_index = 4

sample_applicant = X.iloc[applicant_index:applicant_index+1]
print(f"\nApplicant Data (index {applicant_index}):\n")
print(sample_applicant)

prediction = model.predict(sample_applicant)[0]


print("\nPredicted Loan Status:")
if prediction == 1:
    print("Approved")
else:
    print("Rejected")

result_df = sample_applicant.copy()
result_df['Predicted_Loan_Status'] = "Approved" if prediction == 1 else "Rejected"

print("\nApplicant Details with Prediction:")
display(result_df)